# Generated by Django 3.2.3 on 2023-09-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_auto_20230918_1715"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="shoppingcart",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="unique_in_shopping_cart"
            ),
        ),
    ]
